{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "aas-registry.labels" . | nindent 4 }}
  name: {{ include "aas-registry.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ include "aas-registry.fullname" . }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        # rewriteTarget: /$1
        pathType: Prefix
        backend:
          service:
            name: {{ include "aas-registry.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{ end -}}