apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sm-registry.fullname" . }}-rbac-rules
  labels:
    {{- include "sm-registry.labels" . | nindent 4 }}
data:
  rbac-rules.json: |-
    {{ .Values.rbac.rules | nindent 4 }}