{{- $apiruleEnabled := false }}
{{- range .Values.apirule }}
  {{- if .enabled }}
    {{- $apiruleEnabled = true }}
  {{- end }}
{{- end }}

{{- if and $apiruleEnabled .Values.enabled }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "mqtt.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            notPrincipals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
{{ end -}}
